nom=input("Nombres completos: ")
edad=int(input("Edad: "))
inst=input("Centro de estudios: ")
carr=input("Carrera que estudia: ")
print()
print("Mi nombre es",nom,"tengo",edad,"años de edad,")
print("estudio en el instituto de",inst,"en la carrera de",carr,".")
print()
print("MUCHAS GRACIAS POR TODO :3, HASTA LA PROXIMA!!")
