print("DATOS DEL TRABAJADOR")
Dato1=input("Ingrese sus nombres: ")
Dato2=input("Ingrese suS apellidos: ")
edad=int(input("Ingrese la edad sus edad: "))
DNI=input("N° de DNI: ")
print()
print("Nombres del trabajador: ",Dato1)
print("Apellidos del trabajador: ",Dato2)
print("Edad del trabajador: ",edad)
print("N° del DNI ddel trabajador: ",DNI)
